global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: miller-schackman-api
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: outbound-send-dispatcher
    metrics_path: /metrics
    static_configs:
      - targets: ["outbound-send-dispatcher:9101"]